"""T-005-04: 仕様書 HTML 生成サービス.

クライアント納品向けの「仕様書 (1 ファイル HTML)」を生成する.
構成:
  - <h1> プロジェクト名 + 生成日時 + バージョン
  - 1. ヒアリングサマリー
  - 2. 要件 (タブ単位の集約)
  - 3. 画面リスト
  - 4. 受け入れ基準 (EARS)
  - 5. リスク / 未解決事項

公開 API:
  - render_spec_html(workspace_meta, sections) -> str
  - SpecSection (TypedDict 風 dict)

依存先 (router 側で resolver を注入):
  - hearing_service.get_summary
  - requirements_service.get_aggregated_view
  - design_frames など (将来)

このサービス自体は HTML 構築の純粋関数で DB アクセスしない.
"""
from __future__ import annotations

import html
import logging
from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any, Iterable, Optional

logger = logging.getLogger(__name__)


class SpecHtmlError(RuntimeError):
    pass


@dataclass
class SpecSection:
    title: str
    body_html: str = ""  # 内部 HTML (escape 済みであること)
    bullet_items: list[str] = field(default_factory=list)  # plain text (auto escape)


@dataclass
class SpecMeta:
    project_name: str
    workspace_id: int
    version: str = "draft"
    generated_at: Optional[str] = None
    generator: str = "Build-Factory"


def _esc(s: str) -> str:
    return html.escape(s or "")


def _now_iso() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def _section_to_html(sec: SpecSection, *, index: int) -> str:
    """1 セクションを HTML に."""
    parts = [
        f'<section class="spec-section" id="sec-{index}">',
        f'<h2>{index}. {_esc(sec.title)}</h2>',
    ]
    if sec.body_html:
        parts.append(sec.body_html)
    if sec.bullet_items:
        parts.append("<ul>")
        for item in sec.bullet_items:
            parts.append(f"<li>{_esc(item)}</li>")
        parts.append("</ul>")
    parts.append("</section>")
    return "\n".join(parts)


_HTML_STYLE = """
<style>
  body { font-family: 'Noto Sans JP', -apple-system, sans-serif;
         max-width: 920px; margin: 40px auto; padding: 0 24px;
         color: #0F172A; line-height: 1.7; }
  header { border-bottom: 4px solid #1a6648; padding-bottom: 16px; margin-bottom: 32px; }
  h1 { font-size: 28px; font-weight: 800; margin: 0 0 8px; color: #1a6648; }
  .meta { color: #475569; font-size: 14px; }
  h2 { font-size: 20px; font-weight: 700; margin: 32px 0 12px;
       border-left: 4px solid #1a6648; padding-left: 12px; }
  h3 { font-size: 16px; font-weight: 700; margin: 16px 0 8px; }
  ul { margin: 8px 0; padding-left: 24px; }
  li { margin: 4px 0; }
  .spec-section { margin: 24px 0; }
  footer { margin-top: 64px; padding-top: 16px; border-top: 1px solid #E2E8F0;
           color: #94A3B8; font-size: 12px; text-align: center; }
</style>
""".strip()


def render_spec_html(
    meta: SpecMeta,
    sections: Iterable[SpecSection],
) -> str:
    """仕様書 HTML を 1 ファイル文字列で返す."""
    if not isinstance(meta, SpecMeta):
        raise SpecHtmlError("meta must be SpecMeta")
    if not meta.project_name or not meta.project_name.strip():
        raise SpecHtmlError("project_name must not be empty")
    if not meta.workspace_id or meta.workspace_id <= 0:
        raise SpecHtmlError("workspace_id must be > 0")

    sec_list = list(sections)
    generated_at = meta.generated_at or _now_iso()

    parts: list[str] = [
        "<!doctype html>",
        '<html lang="ja"><head>',
        '<meta charset="utf-8">',
        f'<meta name="generator" content="{_esc(meta.generator)}">',
        f'<meta name="workspace-id" content="{meta.workspace_id}">',
        f'<title>{_esc(meta.project_name)} — 仕様書 ({_esc(meta.version)})</title>',
        _HTML_STYLE,
        "</head><body>",
        "<header>",
        f'<h1>{_esc(meta.project_name)} 仕様書</h1>',
        f'<div class="meta">version: {_esc(meta.version)} '
        f'/ generated: {_esc(generated_at)} '
        f'/ workspace_id: {meta.workspace_id}</div>',
        "</header>",
    ]
    if not sec_list:
        parts.append(
            '<section class="spec-section">'
            '<p style="color:#94A3B8;">(セクションなし)</p>'
            '</section>'
        )
    else:
        for i, sec in enumerate(sec_list, 1):
            parts.append(_section_to_html(sec, index=i))
    parts.append(
        f'<footer>Generated by Build-Factory ({_esc(generated_at)})</footer>'
    )
    parts.append("</body></html>")
    return "\n".join(parts)


# ──────────────────────────────────────────────────────────────────────────
# Helper: 既存 view dict から SpecSection を組み立てる
# ──────────────────────────────────────────────────────────────────────────


def build_sections_from_view(view: dict) -> list[SpecSection]:
    """requirements_service.get_aggregated_view の出力から sections を組み立てる."""
    if not isinstance(view, dict):
        return []
    sections: list[SpecSection] = []
    tabs = view.get("tabs") or {}
    if not isinstance(tabs, dict):
        return []
    # 推奨表示順
    order = [
        ("overview", "1. プロジェクト概要"),
        ("users", "2. 想定ユーザー"),
        ("features", "3. 機能一覧"),
        ("functional", "4. 機能要件"),
        ("nonfunctional", "5. 非機能要件"),
        ("screens", "6. 画面"),
        ("data", "7. データ"),
        ("integrations", "8. 外部連携"),
        ("legal", "9. 法務 / コンプライアンス"),
        ("risks", "10. リスク"),
        ("unresolved", "11. 未解決事項"),
    ]
    for tab_key, title in order:
        rows = tabs.get(tab_key)
        if not rows:
            continue
        items: list[str] = []
        for row in rows:
            if isinstance(row, dict):
                label = row.get("label") or row.get("title") or ""
                value = row.get("value") or row.get("content") or ""
                if isinstance(value, (dict, list)):
                    import json as _json
                    value = _json.dumps(value, ensure_ascii=False)
                items.append(f"{label}: {value}".strip(": "))
            else:
                items.append(str(row))
        sections.append(SpecSection(title=title, bullet_items=items))
    return sections
